# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: CopyFiles@2
  inputs:
    contents: '**/*'
    targetFolder: $(Build.ArtifactStagingDirectory)
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: $(Build.ArtifactStagingDirectory)
    artifactName: 'xml'

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: '188ae9a7-5384-42b0-b181-9c300543a1ae'
    organization: 'gorla-kishore-mas62580'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'sales'
    cliProjectName: 'sales'
  
- task: SonarSource.sonarcloud.ce096e50-6155-4de8-8800-4221aaeed4a1.SonarCloudAnalyze@1
  displayName: 'Run Code Analysis'
- task: PublishCodeCoverageResults@1
  inputs:
    summaryFileLocation: '**/*'
    failIfCoverageEmpty: true
